[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Vary = "Origin"

[context.production]
  environment = { NODE_VERSION = "18" }

[build]
  base = "/"
  publish = "dist/"
  command = "npm run build"